name: Integration Tests

on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: pip install wheel setuptools
    
      - name: Build package
        run: python setup.py bdist_wheel
    
      - name: Upload Python wheel
        uses: actions/upload-artifact@v4
        with:
          name: "Python wheel"
          path: ./dist/*
          if-no-files-found: error

  integration-tests:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.10"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Install dependencies
        run: pip install wheel setuptools
    
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: "Python wheel"

      - name: Install wheel
        run: pip install --find-links=. vsi2tif-*
        shell: bash

      - name: Build and install libvips
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config \
            libglib2.0-dev libexpat1-dev libjpeg-turbo8-dev libpng-dev \
            libtiff-dev libwebp-dev libopenexr-dev liblcms2-dev \
            libimagequant-dev librsvg2-dev libheif-dev liborc-dev \
            libcfitsio-dev meson ninja-build
          wget https://github.com/libvips/libvips/releases/download/v8.17.1/vips-8.17.1.tar.xz
          tar xf vips-8.17.1.tar.xz
          cd vips-8.17.1
          meson setup build --prefix=/usr/local
          meson compile -C build
          sudo meson install -C build
          sudo ldconfig
          vips --version

      - name: Install bftools
        run: |
          wget http://downloads.openmicroscopy.org/latest/bio-formats5.6/artifacts/bftools.zip
          unzip bftools.zip
      
      - name: Download test data
        run: |
          wget https://openslide.cs.cmu.edu/download/openslide-testdata/Olympus/OS-1.zip
          wget https://openslide.cs.cmu.edu/download/openslide-testdata/Olympus/OS-2.zip
          unzip OS-1.zip
          unzip OS-2.zip
          mkdir WSI/
          mv OS-* WSI/
      
      - name: Test single conversion
        run: vsi2tif -i ./WSI/OS-2.vsi -o ./OS-2.tif -b bftools/bfconvert -v 0
        shell: bash

      - name: Test batch conversion
        run: vsi2tif -i ./WSI -o ./converted/ -b bftools/bfconvert -v 0
        shell: bash

      - name: Test batch conversion (no skip)
        run: vsi2tif -i ./WSI -o ./converted/ -b bftools/bfconvert -v 0 --noskip-converted
        shell: bash